server:
  port: 8081


spring:
  application:
    name: oauth2-security-example
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:oauth2db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Security Configuration
  security:
    oauth2:
      authorizationserver:
        client:
          client-app:
            registration:
              client-id: "client-app"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/client-app"
                - "http://localhost:8080/authorized"
              post-logout-redirect-uris:
                - "http://localhost:8080/"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"
            require-authorization-consent: true
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/public-client"
              scopes:
                - "openid"
                - "profile"
                - "read"
            require-authorization-consent: true
    user:
      name: admin
      password: admin123456

# JWT Configuration
jwt:
  access-token:
    expiration: 3600 # 1 hour in seconds
  refresh-token:
    expiration: 86400 # 24 hours in seconds

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.example.oauth2: DEBUG
